export const textStyles = {
  largeText: {
    fontSize: "32px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  h1: {
    fontSize: "26px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  h2: {
    fontSize: "24px",
    fontWeight: "normal",
    lineHeight: 1.5,
    letterSpacing: "0em",
  },
  h3: {
    fontSize: "22px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  h4: {
    fontSize: "20px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  h5: {
    fontSize: "18px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  h6: {
    fontSize: "16px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  button: {
    fontSize: "16px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.04em",
  },
  subtitle1: {
    fontSize: "16px",
    fontWeight: "normal",
    lineHeight: 1.75,
    letterSpacing: "0.04em",
  },
  subtitle1Bold: {
    fontSize: "16px",
    fontWeight: "bold",
    lineHeight: 1.75,
    letterSpacing: "0.04em",
  },
  subtitle2: {
    fontSize: "14px",
    fontWeight: "medium",
    lineHeight: 1.75,
    letterSpacing: "0.04em",
  },
  subtitle2Bold: {
    fontSize: "14px",
    fontWeight: "bold",
    lineHeight: 1.75,
    letterSpacing: "0.04em",
  },
  body1: {
    fontSize: "16px",
    fontWeight: "normal",
    lineHeight: 1.7,
    letterSpacing: "0.04em",
  },
  body2: {
    fontSize: "14px",
    fontWeight: "normal",
    lineHeight: 1.7,
    letterSpacing: "0.04em",
  },
  body3: {
    fontSize: "12px",
    fontWeight: "normal",
    lineHeight: 1.6,
    letterSpacing: "0.03em",
  },
  caption: {
    fontSize: "12px",
    fontWeight: "normal",
    lineHeight: 1.5,
    letterSpacing: "0.0125em",
  },
  captionBold: {
    fontSize: "12px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.0125em",
  },
  overline: {
    fontSize: "10px",
    fontWeight: "normal",
    lineHeight: 1.5,
    letterSpacing: "0.015em",
  },
  overlineBold: {
    fontSize: "10px",
    fontWeight: "bold",
    lineHeight: 1.5,
    letterSpacing: "0.015em",
  },
};
