/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserIdIndexImport } from './routes/$userId/index'

// Create Virtual Routes

const SignupFormLazyImport = createFileRoute('/signup-form')()
const SignupLazyImport = createFileRoute('/signup')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const UserIdHistoryAddLazyImport = createFileRoute('/$userId/history/add')()
const UserIdHistoryHistoryIdLazyImport = createFileRoute(
  '/$userId/history/$historyId',
)()

// Create/Update Routes

const SignupFormLazyRoute = SignupFormLazyImport.update({
  path: '/signup-form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup-form.lazy').then((d) => d.Route))

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UserIdIndexRoute = UserIdIndexImport.update({
  path: '/$userId/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdHistoryAddLazyRoute = UserIdHistoryAddLazyImport.update({
  path: '/$userId/history/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$userId/history/add.lazy').then((d) => d.Route),
)

const UserIdHistoryHistoryIdLazyRoute = UserIdHistoryHistoryIdLazyImport.update(
  {
    path: '/$userId/history/$historyId',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/$userId/history/$historyId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup-form': {
      id: '/signup-form'
      path: '/signup-form'
      fullPath: '/signup-form'
      preLoaderRoute: typeof SignupFormLazyImport
      parentRoute: typeof rootRoute
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/$userId/history/$historyId': {
      id: '/$userId/history/$historyId'
      path: '/$userId/history/$historyId'
      fullPath: '/$userId/history/$historyId'
      preLoaderRoute: typeof UserIdHistoryHistoryIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/$userId/history/add': {
      id: '/$userId/history/add'
      path: '/$userId/history/add'
      fullPath: '/$userId/history/add'
      preLoaderRoute: typeof UserIdHistoryAddLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LoginLazyRoute,
  SignupLazyRoute,
  SignupFormLazyRoute,
  UserIdIndexRoute,
  UserIdHistoryHistoryIdLazyRoute,
  UserIdHistoryAddLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/signup",
        "/signup-form",
        "/$userId/",
        "/$userId/history/$historyId",
        "/$userId/history/add"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/signup-form": {
      "filePath": "signup-form.lazy.tsx"
    },
    "/$userId/": {
      "filePath": "$userId/index.tsx"
    },
    "/$userId/history/$historyId": {
      "filePath": "$userId/history/$historyId.lazy.tsx"
    },
    "/$userId/history/add": {
      "filePath": "$userId/history/add.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
