/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const UserIdIndexLazyImport = createFileRoute('/$userId/')()
const UserIdHistoryAddLazyImport = createFileRoute('/$userId/history/add')()
const UserIdHistoryHistoryIdLazyImport = createFileRoute(
  '/$userId/history/$historyId',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UserIdIndexLazyRoute = UserIdIndexLazyImport.update({
  path: '/$userId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$userId/index.lazy').then((d) => d.Route))

const UserIdHistoryAddLazyRoute = UserIdHistoryAddLazyImport.update({
  path: '/$userId/history/add',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$userId/history/add.lazy').then((d) => d.Route),
)

const UserIdHistoryHistoryIdLazyRoute = UserIdHistoryHistoryIdLazyImport.update(
  {
    path: '/$userId/history/$historyId',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/$userId/history/$historyId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$userId/history/$historyId': {
      id: '/$userId/history/$historyId'
      path: '/$userId/history/$historyId'
      fullPath: '/$userId/history/$historyId'
      preLoaderRoute: typeof UserIdHistoryHistoryIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/$userId/history/add': {
      id: '/$userId/history/add'
      path: '/$userId/history/add'
      fullPath: '/$userId/history/add'
      preLoaderRoute: typeof UserIdHistoryAddLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  UserIdIndexLazyRoute,
  UserIdHistoryHistoryIdLazyRoute,
  UserIdHistoryAddLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$userId/",
        "/$userId/history/$historyId",
        "/$userId/history/add"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$userId/": {
      "filePath": "$userId/index.lazy.tsx"
    },
    "/$userId/history/$historyId": {
      "filePath": "$userId/history/$historyId.lazy.tsx"
    },
    "/$userId/history/add": {
      "filePath": "$userId/history/add.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
